<a href="https://colab.research.google.com/github/JoulesScience/APIconsultarpersonas/blob/master/Pendiente_Reporte_Sicerco_Cali.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import files

# Abre un cuadro de diálogo para seleccionar y subir archivos
# Aqui carga el archivo Base Reporte_Dictamenes de Sicerco
uploaded = files.upload()

# Opcional: ver los nombres de los archivos subidos
for filename in uploaded.keys():
    print(f'Se subió el archivo: {filename}')

Saving Reporte_Dictamenes_28714_1776294000158.XLSX to Reporte_Dictamenes_28714_1776294000158.XLSX
Se subió el archivo: Reporte_Dictamenes_28714_1776294000158.XLSX

In [2]:
# imprimir el nombre del archivo
print(filename)

Reporte_Dictamenes_28714_1776294000158.XLSX

In [3]:
import pandas as pd

# Reemplaza con el nombre del archivo subido
df = pd.read_excel(filename)

# Ver las primeras filas
df.head()

,Número de acreditación del OEC,Nombre del OEC,Número de dictamen,Fecha de emisión del dictamen,Fecha de creación del dictamen,Estado de vigencia,Tipo de identificación del técnico instalador o Constructor,Número de identificación del técnico instalador o Constructor,Razón social del técnico instalador o Constructor,País,Departamento,Municipio,Reglamento técnico asociado al dictamen,Tipo de organismo,Tipo de instalación inspeccionada,Tipo de identificación del Inspector,Numero de identificación del Inspector,Nombre del Inspector,Número de identificación instalación,Anulado
0,17-OIN-036,MAIKO INGENIERIA S.A.S.,131361361,2025-01-14,2026-04-15 09:59:25 AM,Vigente,No conocido,0.0,NO CONOCIDO,Colombia,Caquetá,El Doncello,Resolución 90902 de 2013. RT de instalaciones ...,A,Instalaciones para el suministro de gas en edi...,Cédula de ciudadanía,1117498971,CARLOS ANDRES ROJAS ARREDONDO,201921096135,No
1,17-OIN-036,MAIKO INGENIERIA S.A.S.,134685784,2025-07-12,2026-04-15 09:59:25 AM,Vigente,No conocido,0.0,NO CONOCIDO,Colombia,Caquetá,Puerto Rico,Resolución 90902 de 2013. RT de instalaciones ...,A,Instalaciones para el suministro de gas en edi...,Cédula de ciudadanía,1117498971,CARLOS ANDRES ROJAS ARREDONDO,201902031196,No
2,17-OIN-036,MAIKO INGENIERIA S.A.S.,134831264,2025-07-22,2026-04-15 09:59:25 AM,Vigente,No conocido,0.0,NO CONOCIDO,Colombia,Caquetá,Puerto Rico,Resolución 90902 de 2013. RT de instalaciones ...,A,Instalaciones para el suministro de gas en edi...,Cédula de ciudadanía,1117498971,CARLOS ANDRES ROJAS ARREDONDO,201902034388,No
3,17-OIN-036,MAIKO INGENIERIA S.A.S.,134857763,2025-07-23,2026-04-15 09:59:25 AM,Vigente,No conocido,0.0,NO CONOCIDO,Colombia,Caquetá,Puerto Rico,Resolución 90902 de 2013. RT de instalaciones ...,A,Instalaciones para el suministro de gas en edi...,Cédula de ciudadanía,1117498971,CARLOS ANDRES ROJAS ARREDONDO,201902031982,No
4,17-OIN-036,MAIKO INGENIERIA S.A.S.,134883646,2025-07-24,2026-04-15 09:59:25 AM,Vigente,No conocido,0.0,NO CONOCIDO,Colombia,Caquetá,Puerto Rico,Resolución 90902 de 2013. RT de instalaciones ...,A,Instalaciones para el suministro de gas en edi...,Cédula de ciudadanía,1117498971,CARLOS ANDRES ROJAS ARREDONDO,201902034868,No

In [4]:
len(df)

5141

In [5]:
df['Reglamento técnico asociado al dictamen'].unique()

array(['Resolución 90902 de 2013. RT de instalaciones internas de gas combustible',
       'Resolución 40245 de 7 de marzo de 2016 Rt Para cilindros y tanques estacionarios utilizados en la prestación del servicio público domiciliario de gas licuado de petróleo (GLP) y sus procesos de mantenimiento.'],
      dtype=object)

In [6]:
df_filtrado = df[
    df['Reglamento técnico asociado al dictamen']
    == 'Resolución 90902 de 2013. RT de instalaciones internas de gas combustible'
]

print(df_filtrado)

     Número de acreditación del OEC           Nombre del OEC  \
0                        17-OIN-036  MAIKO INGENIERIA S.A.S.
1                        17-OIN-036  MAIKO INGENIERIA S.A.S.
2                        17-OIN-036  MAIKO INGENIERIA S.A.S.
3                        17-OIN-036  MAIKO INGENIERIA S.A.S.
4                        17-OIN-036  MAIKO INGENIERIA S.A.S.
...                             ...                      ...
5136                     17-OIN-036  MAIKO INGENIERIA S.A.S.
5137                     17-OIN-036  MAIKO INGENIERIA S.A.S.
5138                     17-OIN-036  MAIKO INGENIERIA S.A.S.
5139                     17-OIN-036  MAIKO INGENIERIA S.A.S.
5140                     17-OIN-036  MAIKO INGENIERIA S.A.S.

     Número de dictamen Fecha de emisión del dictamen  \
0             131361361                    2025-01-14
1             134685784                    2025-07-12
2             134831264                    2025-07-22
3             134857763                    2025-07-23
4             134883646                    2025-07-24
...                 ...                           ...
5136          131562048                    2025-01-30
5137          131596156                    2025-02-03
5138          131729945                    2025-02-14
5139          131252064                    2025-01-03
5140          131536573                    2025-01-28

     Fecha de creación del dictamen Estado de vigencia  \
0            2026-04-15 09:59:25 AM            Vigente
1            2026-04-15 09:59:25 AM            Vigente
2            2026-04-15 09:59:25 AM            Vigente
3            2026-04-15 09:59:25 AM            Vigente
4            2026-04-15 09:59:25 AM            Vigente
...                             ...                ...
5136         2025-10-15 08:23:38 PM            Vigente
5137         2025-10-15 08:23:38 PM            Vigente
5138         2025-10-15 08:23:38 PM            Vigente
5139         2025-10-15 08:23:37 PM            Vigente
5140         2025-10-15 08:23:37 PM            Vigente

     Tipo de identificación del técnico instalador o Constructor  \
0                                           No conocido
1                                           No conocido
2                                           No conocido
3                                           No conocido
4                                           No conocido
...                                                 ...
5136                                        No conocido
5137                                        No conocido
5138                                        No conocido
5139                                        No conocido
5140                                        No conocido

      Número de identificación del técnico instalador o Constructor  \
0                                                   0.0
1                                                   0.0
2                                                   0.0
3                                                   0.0
4                                                   0.0
...                                                 ...
5136                                                0.0
5137                                                0.0
5138                                                0.0
5139                                                0.0
5140                                                0.0

     Razón social del técnico instalador o Constructor      País Departamento  \
0                                          NO CONOCIDO  Colombia      Caquetá
1                                          NO CONOCIDO  Colombia      Caquetá
2                                          NO CONOCIDO  Colombia      Caquetá
3                                          NO CONOCIDO  Colombia      Caquetá
4                                          NO CONOCIDO  Colombia      Caquetá
...                                                ...       ...          ...
5136                                       NO CONOCIDO  Colombia      Caquetá
5137                                       NO CONOCIDO  Colombia      Caquetá
5138                                       NO CONOCIDO  Colombia      Caquetá
5139                                       NO CONOCIDO  Colombia      Caquetá
5140                                       NO CONOCIDO  Colombia      Caquetá

        Municipio            Reglamento técnico asociado al dictamen  \
0     El Doncello  Resolución 90902 de 2013. RT de instalaciones ...
1     Puerto Rico  Resolución 90902 de 2013. RT de instalaciones ...
2     Puerto Rico  Resolución 90902 de 2013. RT de instalaciones ...
3     Puerto Rico  Resolución 90902 de 2013. RT de instalaciones ...
4     Puerto Rico  Resolución 90902 de 2013. RT de instalaciones ...
...           ...                                                ...
5136    Florencia  Resolución 90902 de 2013. RT de instalaciones ...
5137    Florencia  Resolución 90902 de 2013. RT de instalaciones ...
5138    Florencia  Resolución 90902 de 2013. RT de instalaciones ...
5139    Florencia  Resolución 90902 de 2013. RT de instalaciones ...
5140    Florencia  Resolución 90902 de 2013. RT de instalaciones ...

     Tipo de organismo                  Tipo de instalación inspeccionada  \
0                    A  Instalaciones para el suministro de gas en edi...
1                    A  Instalaciones para el suministro de gas en edi...
2                    A  Instalaciones para el suministro de gas en edi...
3                    A  Instalaciones para el suministro de gas en edi...
4                    A  Instalaciones para el suministro de gas en edi...
...                ...                                                ...
5136                 A  Instalaciones para el suministro de gas en edi...
5137                 A  Instalaciones para el suministro de gas en edi...
5138                 A  Instalaciones para el suministro de gas en edi...
5139                 A  Instalaciones para el suministro de gas en edi...
5140                 A  Instalaciones para el suministro de gas en edi...

     Tipo de identificación del Inspector  \
0                    Cédula de ciudadanía
1                    Cédula de ciudadanía
2                    Cédula de ciudadanía
3                    Cédula de ciudadanía
4                    Cédula de ciudadanía
...                                   ...
5136                 Cédula de ciudadanía
5137                 Cédula de ciudadanía
5138                 Cédula de ciudadanía
5139                 Cédula de ciudadanía
5140                 Cédula de ciudadanía

      Numero de identificación del Inspector          Nombre  del Inspector  \
0                                 1117498971  CARLOS ANDRES ROJAS ARREDONDO
1                                 1117498971  CARLOS ANDRES ROJAS ARREDONDO
2                                 1117498971  CARLOS ANDRES ROJAS ARREDONDO
3                                 1117498971  CARLOS ANDRES ROJAS ARREDONDO
4                                 1117498971  CARLOS ANDRES ROJAS ARREDONDO
...                                      ...                            ...
5136                              1117497569            YASNO CARLOS FABIAN
5137                              1117497569            YASNO CARLOS FABIAN
5138                              1117497569            YASNO CARLOS FABIAN
5139                              1117497569            YASNO CARLOS FABIAN
5140                              1117497569            YASNO CARLOS FABIAN

     Número de identificación instalación Anulado
0                            201921096135      No
1                            201902031196      No
2                            201902034388      No
3                            201902031982      No
4                            201902034868      No
...                                   ...     ...
5136                            291579714      No
5137                          45146162022      No
5138                           2100921209      No
5139                             22822109      No
5140                          43301822022      No

[4853 rows x 20 columns]

In [7]:
#Aqui carga la base de inspecciín cali, Pasto,
# Abre un cuadro de diálogo para seleccionar y subir archivos
# Aqui carga el archivo Base Reporte_Dictamenes de Sicerco
uploaded = files.upload()

# Opcional: ver los nombres de los archivos subidos
for filename_2 in uploaded.keys():
    print(f'Se subió el archivo: {filename_2}')

Saving BASE DATOS CALI 2026.xlsx to BASE DATOS CALI 2026.xlsx
Se subió el archivo: BASE DATOS CALI 2026.xlsx

In [8]:
# imprimir el nombre del archivo
print(filename_2)

BASE DATOS CALI 2026.xlsx

In [9]:
import pandas as pd

# Reemplaza con el nombre del archivo subido
df_BaseInspecc = pd.read_excel(filename_2)

# Ver las primeras filas
df_BaseInspecc.head()

/usr/local/lib/python3.12/dist-packages/openpyxl/worksheet/_reader.py:223: UserWarning: Cell AC536 is marked as a date but the serial value 140404376.0 is outside the limits for dates. The cell will be treated as an error.
  warn(msg)
/usr/local/lib/python3.12/dist-packages/openpyxl/worksheet/_reader.py:329: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)

,No. INFORME,OBSERVACION INFORME,PUNTOS ADICIONALES,FECHA INSPECCIÓN,No. CEDULA,No. CONTRATO Y/O POLIZA,No. MEDIDOR,NOMBRE USUARIO,No. CELULAR USUARIO,DIRECCIÓN USUARIO,...,RESULTADO,REGISTRO FOTOGRAFICO,FECHA DE REPORTE SICERCO,REPORTE ACTA DISTRIBUIDOR,FECHA CORTE / LIQUIDACIÓN,CONSIGNACION / FACTURACION ELECTRONICA,FECHA CONSIGNACIÓN / FACTURACIÓN ELECTRONICA,COSTO,PAGO A INSPECTOR,OBSERVACIONES
0,139237956,PDT FOTOS,SANDRA,2026-01-07 00:00:00,CéDULA 66927904,NaN,-----,ANAYIVI PACHECO DONEY,3014266923,KR 29 B OESTE CL 18 B -6 MZ T6 CADA 32 B PISO 02,...,INFORME DE INSPECCION,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-----
1,139341055,PDT FOTOS,SANDRA,2026-01-14 00:00:00,NaN,CEDULA 38563166,-,DORIS ANA ARIAS VIVERO,3174963366,CL 16B KR 29 OESTE - 79 MZ N1 CASA 29B PISO 01,...,INFORME DE INSPECCION,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,INSPECCIONADA
2,139341114,PDT FOTOS,NaN,2026-01-15 00:00:00,NaN,CéDULA 30515323,-----,MARÍA NOELVA LÓPEZ MONTOYA,3104623123\n 300800890,KR 3 NORTE CL 14 OESTE -97 APTO 101,...,INFORME DE INSPECCION,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,------
3,139341177,PDT FOTOS,NaN,2026-01-15 00:00:00,NaN,CéDULA 1130595324,----,NATHALIA TORRES SUÁREZ,3008324441,KR 43 A CL 37 -64 APTO 101,...,INFORME DE INSPECCION,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,------
4,139364021,corregir medida de psi y señor oscar el mker 0...,SANDRA,141042135,NaN,CéDULA 66949470,------,PAULA ANDREA CARABALI GONZÁLEZ,3162514962,CL 16 KR 24 C OESTE -99 MZ J14 CASA 6A PISO 01,...,INFORME DE INSPECCION,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-------

In [11]:
len(df_BaseInspecc)

956

In [12]:
# Actas de Inspección pendientes de cargue a Sicerco:

# Asegurar que ambas columnas sean del mismo tipo (recomendado)
df_BaseInspecc["No. INFORME"] = df_BaseInspecc["No. INFORME"].astype(str)
df_filtrado["Número de dictamen"] = df_filtrado["Número de dictamen"].astype(str)

# Filtrar los registros que NO están en el otro dataframe Base Sicerco
df_resultado = df_BaseInspecc[
    ~df_BaseInspecc["No. INFORME"].isin(df_filtrado["Número de dictamen"])
]

# Ver resultado
print(df_resultado)

# Exportar a Excel
df_resultado.to_excel("df_resultado.xlsx", index=False)

/tmp/ipykernel_23794/1557775134.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filtrado["Número de dictamen"] = df_filtrado["Número de dictamen"].astype(str)

    No. INFORME                               OBSERVACION  INFORME  \
0     139237956                                         PDT FOTOS
1     139341055                                          PDT FOTOS
2     139341114                                          PDT FOTOS
3     139341177                                          PDT FOTOS
4     139364021  corregir medida de psi y señor oscar el mker 0...
..          ...                                                ...
951   141074675                                                NaN
952   141074727                                                NaN
953   141074772                                                NaN
954   141074976                                                NaN
955   141084042                                                 OK

    PUNTOS ADICIONALES     FECHA INSPECCIÓN       No. CEDULA  \
0               SANDRA  2026-01-07 00:00:00  CéDULA 66927904
1               SANDRA  2026-01-14 00:00:00              NaN
2                  NaN  2026-01-15 00:00:00              NaN
3                  NaN  2026-01-15 00:00:00              NaN
4               SANDRA            141042135              NaN
..                 ...                  ...              ...
951                NaN  2026-04-25 00:00:00              NaN
952                NaN  2026-04-25 00:00:00              NaN
953                NaN  2026-04-25 00:00:00              NaN
954                NaN  2026-04-25 00:00:00              NaN
955      REVISADA ANYI  2026-04-28 00:00:00              NaN

    No. CONTRATO Y/O POLIZA No. MEDIDOR                     NOMBRE USUARIO  \
0                       NaN       -----              ANAYIVI PACHECO DONEY
1           CEDULA 38563166           -             DORIS ANA ARIAS VIVERO
2           CéDULA 30515323       -----         MARÍA NOELVA LÓPEZ MONTOYA
3         CéDULA 1130595324        ----             NATHALIA TORRES SUÁREZ
4           CéDULA 66949470      ------     PAULA ANDREA CARABALI GONZÁLEZ
..                      ...         ...                                ...
951                  354763       97685            GLORIA PATRICIA CAICEDO
952                  305278       60183        JOSE WILSON MARTINEZ OSORIO
953                 3089689      354702  JHAMILTON DAVID MELINDRES VASQUEZ
954                 3129583   745385625              ISRAEL FERNANDEZ LUNA
955                  209145     7498810              GLORIA KARINA MONTAÑO

        No. CELULAR USUARIO                                 DIRECCIÓN USUARIO  \
0                3014266923  KR 29 B OESTE CL 18 B -6 MZ T6 CADA 32 B PISO 02
1                3174963366    CL 16B KR 29 OESTE - 79 MZ N1 CASA 29B PISO 01
2    3104623123\n 300800890               KR 3 NORTE CL 14 OESTE -97 APTO 101
3                3008324441                        KR 43 A CL 37 -64 APTO 101
4                3162514962    CL 16 KR 24 C OESTE -99 MZ J14 CASA 6A PISO 01
..                      ...                                               ...
951              3126641106                            KR 1A BIS CL 58 2 - 24
952              3117225398                       KR 28M1 CL 31A - 59 PISO 02
953              3176440802           CL 15 KR 30 OESTE - 53 TORRE G APTO 303
954              3128615048           CL 15 KR 30 OESTE - 53 TORRE M APTO 401
955              3108959984                            CL 71 KR 4C NORTE - 63

     ...                   RESULTADO REGISTRO FOTOGRAFICO  \
0    ...       INFORME DE INSPECCION                  NaN
1    ...       INFORME DE INSPECCION                  NaN
2    ...       INFORME DE INSPECCION                  NaN
3    ...       INFORME DE INSPECCION                  NaN
4    ...       INFORME DE INSPECCION                  NaN
..   ...                         ...                  ...
951  ...  CERTIFICADO DE CONFORMIDAD                  NaN
952  ...  CERTIFICADO DE CONFORMIDAD                  NaN
953  ...  CERTIFICADO DE CONFORMIDAD                  NaN
954  ...  CERTIFICADO DE CONFORMIDAD                  NaN
955  ...  CERTIFICADO DE CONFORMIDAD                   SI

     FECHA DE REPORTE SICERCO REPORTE ACTA DISTRIBUIDOR  \
0                         NaN                       NaN
1                         NaN                       NaN
2                         NaN                       NaN
3                         NaN                       NaN
4                         NaN                       NaN
..                        ...                       ...
951                       NaN                       NaN
952                       NaN                       NaN
953                       NaN                       NaN
954                       NaN                       NaN
955                LISTO ANYI                       NaN

    FECHA CORTE / LIQUIDACIÓN CONSIGNACION / FACTURACION ELECTRONICA  \
0                         NaN                                    NaN
1                         NaN                                    NaN
2                         NaN                                    NaN
3                         NaN                                    NaN
4                         NaN                                    NaN
..                        ...                                    ...
951                       NaN                                    NaN
952                       NaN                                    NaN
953                       NaN                                    NaN
954                       NaN                                    NaN
955                       NaN                                    NaN

    FECHA CONSIGNACIÓN / FACTURACIÓN ELECTRONICA  COSTO PAGO A INSPECTOR  \
0                                            NaN    NaN              NaN
1                                            NaN    NaN              NaN
2                                            NaN    NaN              NaN
3                                            NaN    NaN              NaN
4                                            NaN    NaN              NaN
..                                           ...    ...              ...
951                                          NaN    NaN              NaN
952                                          NaN    NaN              NaN
953                                          NaN    NaN              NaN
954                                          NaN    NaN              NaN
955                                          NaN    NaN              NaN

                                         OBSERVACIONES
0                                                -----
1                                        INSPECCIONADA
2                                               ------
3                                               ------
4                                              -------
..                                                 ...
951  certificado \n fecha de solicitud de inspecció...
952  certificado \n fecha de última inspección : --...
953  certificado \n fecha de solicitud de inspecció...
954  certificado \n fecha de solicitud de inspecció...
955                                        CERTIFICADA

[648 rows x 36 columns]

In [14]:
# Descragar el Excel de la pendientes a Sicerco:
files.download('df_resultado.xlsx')